### ISSUE TITLE
Erreur de génération du PDF

### ISSUE THREAD

**Issue by ariaconseil** [Eoxia/dolifraispro#26]
Bonjour,

Sur une nouvelle installation (sous Debian) de Dolibarr 18.0.5 et PHP 7.4.33 j’ai un soucis de génération du PDF.

![IMG_3029](https://github.com/Eoxia/dolifraispro/assets/46999041/1f338a57-9d69-4765-8d70-101d6fcaf788)

J’ai modifié les droits sur /var/lib/dolibarr/documents et /usr/share/dolibarr/htdocs/custom/dolifraispro mais cela ne change rien.

L'accès au module affiche également une erreur.

![IMG_3030](https://github.com/Eoxia/dolifraispro/assets/46999041/697196c5-08f9-4449-8332-52c7d97c06ba)

**Comment by lmag** [comment]
Il faut installer la librairie afin de générer les pdf sur le serveur, cette option est disponible sur les hébergements [O2s](https://www.o2switch.fr/)

**Comment by ariaconseil** [comment]
Bonjour, 
Je ne suis pas en mode hébergé, mon dolibarr est en local.

**Comment by lmag** [comment]
Bonjour, pour de l'assistance gratuite je vous conseil de passer sur le forum de Dolibarr 👍 https://www.dolibarr.fr/forum/t/module-digirisk-document-unique/37119
Il y aura plus de réponses que sur GitHub
